# Generated by Django 4.0.5 on 2022-08-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_name', models.CharField(max_length=100)),
                ('advert_company', models.CharField(max_length=100)),
                ('advert_city', models.CharField(max_length=20)),
                ('advert_date', models.DateField()),
                ('advert_desc', models.CharField(max_length=500)),
                ('advert_experience', models.CharField(max_length=25)),
                ('education_level', models.CharField(max_length=30)),
            ],
        ),
    ]
