# Generated by Django 4.0.5 on 2022-08-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_date',
            field=models.DateField(auto_created=True),
        ),
    ]
