# Generated by Django 4.0.5 on 2022-08-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0018_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='company'),
        ),
    ]
